    name: Spotless Apply

    on:
      push:
        branches: [RPC]  # O cualquier rama principal
      pull_request:
        branches: [RPC]  # O cualquier rama principal
          # Dispatch or Manual triggers
        workflow_dispatch:

    jobs:
      spotless:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Set up JDK
            uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
            with:
            java-version: 17
            distribution: temurin
          - name: Apply Spotless formatting
            run: ./gradlew spotlessApply
          - name: Commit changes
            run: |
              git config --local user.email "noreply@github.com"
              git config --local user.name "GitHub Actions"
              git add .
              git commit -m "Apply Spotless formatting"
              git push
